In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = [1,0]
s2 = [3,1]
s3 = [3,-1]
s1.append(1)
s2.append(1)
s3.append(1)

In [3]:
s1t=np.transpose(s1)
s2t=np.transpose(s2)
s3t=np.transpose(s3)
print("Transpose")
print(s1t)
print(s2t)
print(s3t)

Transpose
[1 0 1]
[3 1 1]
[ 3 -1  1]


In [4]:
s1ts1=np.dot(s1t,s1)
s1ts2=np.dot(s1t,s2)
s1ts3=np.dot(s1t,s3)
s2ts1=np.dot(s2t,s1)
s2ts2=np.dot(s2t,s2)
s2ts3=np.dot(s2t,s3)
s3ts1=np.dot(s3t,s1)
s3ts2=np.dot(s3t,s2)
s3ts3=np.dot(s3t,s3)

In [5]:
x=np.array([[s1ts1,s1ts2,s1ts3],[s2ts1,s2ts2,s2ts3],[s3ts1,s3ts2,s3ts3]])

In [6]:
xt=np.transpose(x)
xtx=np.dot(xt,x)
xtxi=np.linalg.inv(xtx)

In [7]:
y=np.array([-1,1,1])
xty=np.dot(xt,y)
bhat=np.dot(xtxi,xty)

In [8]:
w=np.array([])
w=bhat[0] *s1t+bhat[1]*s2t+bhat[2]*s3t
print("\nw",w)


w [ 1.0000000e+00  4.4408921e-16 -2.0000000e+00]


In [9]:
b=np.array(round(w[2]))
w=np.array([w[0],w[1]])

In [10]:
x=int(input("Enter x "))
y=int(input("Enter y "))

Enter x 100
Enter y 100


In [11]:
p=np.array([x,y])
res=round(np.dot(w,p))
print("\nRes",res)


Res 100


In [12]:
if(res>b):
    print("\nPositively Classified")
elif (res<b):
    print("\nNegatively Classified")


Positively Classified
